// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: ventas.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VentasServiceClient is the client API for VentasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VentasServiceClient interface {
	SendData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*OrderResponse, error)
}

type ventasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVentasServiceClient(cc grpc.ClientConnInterface) VentasServiceClient {
	return &ventasServiceClient{cc}
}

func (c *ventasServiceClient) SendData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/tarea2.protos.VentasService/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VentasServiceServer is the server API for VentasService service.
// All implementations must embed UnimplementedVentasServiceServer
// for forward compatibility
type VentasServiceServer interface {
	SendData(context.Context, *Data) (*OrderResponse, error)
	mustEmbedUnimplementedVentasServiceServer()
}

// UnimplementedVentasServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVentasServiceServer struct {
}

func (UnimplementedVentasServiceServer) SendData(context.Context, *Data) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}
func (UnimplementedVentasServiceServer) mustEmbedUnimplementedVentasServiceServer() {}

// UnsafeVentasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VentasServiceServer will
// result in compilation errors.
type UnsafeVentasServiceServer interface {
	mustEmbedUnimplementedVentasServiceServer()
}

func RegisterVentasServiceServer(s grpc.ServiceRegistrar, srv VentasServiceServer) {
	s.RegisterService(&VentasService_ServiceDesc, srv)
}

func _VentasService_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VentasServiceServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tarea2.protos.VentasService/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VentasServiceServer).SendData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// VentasService_ServiceDesc is the grpc.ServiceDesc for VentasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VentasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tarea2.protos.VentasService",
	HandlerType: (*VentasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendData",
			Handler:    _VentasService_SendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ventas.proto",
}
